name: cc-gnn
program: experiments.cc.test
method: grid
parameters:
  dim_hidden:
    values: [32]
  dim_plane_pe:
    values: [0]
  num_layers:
    values: [3]
  flags_layer:
    values: ["gin","gcn"]
  flags_plane_agg:
    values: [""]
  lr_start:
    values: [1e-3]
  total_epoch:
    values: [100]
  batch_size:
    values: [256]
  seed:
    values: [0,1,2,3,4]
command:
  - ${env}
  - python3
  - -m
  - ${program}
  - ${args}

#173k