name: exp
program: experiments.exp
method: grid
parameters:
  dim_hidden:
    values: [64]
  dim_plane_pe:
    values: [16]
  num_layers:
    values: [3]
  flags_layer:
    values: ["plane_no_edge"]
  flags_plane_agg:
    values: ["n_t_b_gr_cr"]
  flags_mlp_factor:
    values: [2]
  lr_start:
    values: [1e-3]
  total_epoch:
    values: [50]
  batch_size:
    values: [256]
  total_split:
    values: [10]
  cur_split:
    values: [0,1,2,3,4,5,6,7,8,9]
  seed:
    values: [0]
command:
  - ${env}
  - python3
  - -m
  - ${program}
  - ${args}