name: p3r
program: experiments.p3r
method: grid
parameters:
  dim_hidden:
    values: [32, 64]
  dim_plane_pe:
    values: [16]
  num_layers:
    values: [2, 3]
  flags_layer:
    values: ["gin"]
  flags_plane_agg:
    values: [""]
  flags_mlp_factor:
    values: [2]
  lr_start:
    values: [1e-3, 1e-4]
  total_epoch:
    values: [100]
  batch_size:
    values: [128]
  total_split:
    values: [10]
  cur_split:
    values: [0,1,2,3,4,5,6,7,8,9]
  seed:
    values: [0]
command:
  - ${env}
  - python3
  - -m
  - ${program}
  - ${args}